name: dependency_manager
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  lib_a:
    git:
      url: https://github.com/Vanethos/dm_lib_a.git
      ref: dm_ref_a

  lib_b:
    git:
      url: https://github.com/Vanethos/dm_lib_b.git
      ref: dm_ref_b

  lib_c:
    git:
      url: https://github.com/Vanethos/dm_lib_c.git
      ref: dm_ref_c

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
